# Generated by Django 3.0.8 on 2020-07-05 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200705_1032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='clients',
        ),
    ]
