# Generated by Django 3.0.8 on 2020-07-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200706_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
