# Generated by Django 3.0.8 on 2020-07-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20200716_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='away_odds',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='draw_odds',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='home_odds',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='prediction_odds',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
