# Generated by Django 3.0.8 on 2020-07-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20200716_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
